apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 362928919640.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:8ac6b4e2f47f608d4295cdcd98b877b75f61ddfe
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: earphones-service
  labels:
    app: earphones
spec:
  type: ClusterIP
  selector:
    app: earphones
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
